<a href="https://colab.research.google.com/github/su-dipta/python_basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#creating an array or matrix
# a matrix is 2 dimensional array

a = np.array([[3, 4, 5],
            [7, -9, 8],
             [12, 11, -1]])

#rank of a matrix
print("\nRank of a:", np.linalg.matrix_rank(a))

# Trace of matrix a (Trace = sum of diagonal elements , here for example: trace = 3-9-1)
print("\nTrace of a:", np.trace(a))

# Determinant of a matrix
print("\nDeterminant of a:", np.linalg.det(a))

# Inverse of matrix a
print("\nInverse of a:\n", np.linalg.inv(a))


Rank of a: 3

Trace of a: -7

Determinant of a: 1100.0000000000007

Inverse of a:
 [[-0.07181818  0.05363636  0.07      ]
 [ 0.09363636 -0.05727273  0.01      ]
 [ 0.16818182  0.01363636 -0.05      ]]


In [2]:
a = np.array([[3, 4, 5],
            [7, -9, 8],
             [12, 11, -1]])

print(np.trace(a))

-7


In [17]:
a = np.array([[3, 4, 5],
            [7, -9, 8],
             [12, 11, -1]])

b =  np.array([[1, 2, 3],
            [2, 1, 4],
             [0, 2, 1]])
c = np.dot(a,b)
print(c.T,"\n")
print(c)

[[ 11 -11  34]
 [ 20  21  33]
 [ 30  -7  79]] 

[[ 11  20  30]
 [-11  21  -7]
 [ 34  33  79]]


In [18]:
#eigen value and eigen vectors of a matrix

a = np.array([[3, 4, 5],
            [7, -9, 8],
             [12, 11, -1]])

eval, evec = np.linalg.eig(a)
print("eigen values of this matrix are ", eval, "\n")
print("eigen vectors of this matrix are \n" , evec)

eigen values of this matrix are  [ 13.54322261  -5.34367442 -15.19954819] 

eigen vectors of this matrix are 
 [[ 0.51438507  0.6027327   0.00719052]
 [ 0.42420768 -0.38058431 -0.79345275]
 [ 0.7452891  -0.70133364  0.60858937]]


In [ ]:
b = np.array([[1, 2, 3],
            [2, 1, 4],
             [0, 2, 1]])
eval, evec = np.linalg.eig(b)
print(eval)

[-1.76873431 -0.1157494   4.8844837 ]


In [ ]:
b = np.array([[1, 4],
            [2, 3]])

eval, evec = np.linalg.eig(b)
print(eval)
print(np.round(evec,2))

[-1.  5.]
[[-0.89 -0.71]
 [ 0.45 -0.71]]


In [ ]:
#matrix multiplication

a = np.array([[1, 4, 5,4],
            [2, 3, 6,5],
             [3, 5, 7,6]])

b = np.array([[5, 10, 15],
             [21, 0, 6],
             [7, 8, -8]])

c = np.matmul(b,a)
print(c)
print(c.reshape(-1))

[[ 70 125 190 160]
 [ 39 114 147 120]
 [ -1  12  27  20]]
[ 70 125 190 160  39 114 147 120  -1  12  27  20]


In [20]:
#Sorting

matrix = np.array([[3, 1, 4],
                   [1, 5, 9],
                   [2, 6, 5]])

# Sort rows of the matrix
sorted_rows = np.sort(matrix, axis=1)
print("Sorted rows:")
print(sorted_rows)

# Sort columns of the matrix
sorted_columns = np.sort(matrix, axis=0)
print("\nSorted columns:")
print(sorted_columns)

Sorted rows:
[[1 3 4]
 [1 5 9]
 [2 5 6]]

Sorted columns:
[[1 1 4]
 [2 5 5]
 [3 6 9]]


In [23]:
matrix = np.array([[3, 1, 4],
                   [1, 5, 9],
                   [2, 6, 5]])

# Calculate mean of rows and columns
row_means = np.mean(matrix, axis=1)
col_means = np.mean(matrix, axis=0)
print("row_means ", row_means)
print("col_means ", col_means)

row_means  [2.66666667 5.         4.33333333]
col_means  [2. 4. 6.]


In [ ]:
# Create a sample matrix
matrix = np.array([[3, 1, 4],
                   [1, 5, 9],
                   [2, 6, 5]])

# Calculate sum of rows and columns
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)

# Calculate mean of rows and columns
row_means = np.mean(matrix, axis=1)
col_means = np.mean(matrix, axis=0)

# Calculate maximum of rows and columns
row_max = np.max(matrix, axis=1)
col_max = np.max(matrix, axis=0)

# Calculate minimum of rows and columns
row_min = np.min(matrix, axis=1)
col_min = np.min(matrix, axis=0)

# Print the results
print("Sum of rows:", row_sums)
print("Sum of columns:", col_sums)
print("Mean of rows:", row_means)
print("Mean of columns:", col_means)
print("Maximum of rows:", row_max)
print("Maximum of columns:", col_max)
print("Minimum of rows:", row_min)
print("Minimum of columns:", col_min)

Sum of rows: [ 8 15 13]
Sum of columns: [ 6 12 18]
Mean of rows: [2.66666667 5.         4.33333333]
Mean of columns: [2. 4. 6.]
Maximum of rows: [4 9 6]
Maximum of columns: [3 6 9]
Minimum of rows: [1 1 2]
Minimum of columns: [1 1 4]


In [ ]:
def process_matrices(matrix1, matrix2):

    # Step 1: Multiply the matrices using NumPy
    result_matrix = np.dot(matrix1, matrix2)

    # Step 2: Calculate the trace of the resulting matrix
    trace_result = np.trace(result_matrix)

    # Step 3: Check if the trace exceeds the sum of the first row elements of either matrix
    #print(matrix1[0, 0:2])
    sum_first_row_matrix1 = np.sum(matrix1[0, :])
    sum_first_row_matrix2 = np.sum(matrix2[0, :])

    if trace_result > sum_first_row_matrix1:
        message = f"Trace is greater than the first row elements sum of matrix 1 ({sum_first_row_matrix1})"
    elif trace_result > sum_first_row_matrix2:
        message = f"Trace is greater than the first row elements sum of matrix 2 ({sum_first_row_matrix2})"
    else:
        message = "Trace does not exceed the sum of the first row elements of either matrix."

    # Step 4: Add the trace to the diagonal elements of the satisfied matrix
    satisfied_matrix = result_matrix + trace_result * np.eye(result_matrix.shape[0])

    # Step 5: Calculate the eigenvalues and eigenvectors of the resulting matrix
    eigenvalues, eigenvectors = np.linalg.eig(satisfied_matrix)

    #Step 6:

    #sorting rows of the satisfied matrix:
    sorted_rows = np.sort(satisfied_matrix, axis=1)
    print("sorted rows \n", sorted_rows)


    #sorting columns of the satisfied matrix:
    sorted_columns = np.sort(satisfied_matrix, axis=0)
    print("\nsorted columns \n", sorted_columns, "\n \n")

    return result_matrix, trace_result, message, satisfied_matrix, eigenvalues, eigenvectors

# Define two 3x3 matrices
matrix1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Call the function to process the matrices
result_matrix, trace_result, message, satisfied_matrix, eigenvalues, eigenvectors = process_matrices(matrix1, matrix2)

print(message)

print("\nResulting Matrix:")
print(satisfied_matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


[1 2]
sorted rows 
 [[ 18.  24. 219.]
 [ 54.  84. 258.]
 [114. 138. 279.]]

sorted columns 
 [[ 84.  24.  18.]
 [138. 114.  54.]
 [219. 258. 279.]] 
 

Trace is greater than the first row elements sum of matrix 1 (6)

Resulting Matrix:
[[219.  24.  18.]
 [ 84. 258.  54.]
 [138. 114. 279.]]

Eigenvalues:
[376.26987658 190.73012342 189.        ]

Eigenvectors:
[[ 0.17412685  0.59431808  0.40824829]
 [ 0.5086532  -0.10172622 -0.81649658]
 [ 0.84317955 -0.79777052  0.40824829]]
